### ISSUE TITLE
Draw shapes, and move them around, single canvas

### ISSUE THREAD

**Issue by Noitidart** [williammalone/Simple-HTML5-Drawing-App#7]
Hi there,
I was reading your tutorial here and then was looking for the comments section but only found your github - http://www.williammalone.com/articles/create-html5-canvas-javascript-drawing-app/

I am trying to create a canvas editor as this firefox addon has done - https://addons.mozilla.org/en-US/firefox/addon/nimbus-screenshot/?src=userprofile

They draw shapes on a single canvas, and when i mouse over that shape they show "end points" on it, and i can click and drag the end points to resize/reshape arrow or square or circle. And move it around even. They have done this magic all on a single canvas. I was hoping to do the same too, but couldn't find a tutorial as nice as yours.

Could you please write about how they did this?

Thanks

**Comment by williammalone** [comment]
Thanks Noitidart.  That is a great idea for an article.  I'll keep it in mind when I am planning my next article.  Cheers!

**Comment by Noitidart** [comment]
Thanks so much! I will definitely use that article to implement in my addon. :)

**Comment by Noitidart** [comment]
Hey @williammalone my addon just got approved. But I plan to use the info from that article in my addon here :) https://addons.mozilla.org/en-US/firefox/addon/nativeshot/

**Comment by williammalone** [comment]
Congratulations your new addon Noitidart!
