### ISSUE TITLE
Touch Support doesn't appear to be working

### ISSUE THREAD

**Issue by edlisten** [williammalone/Simple-HTML5-Drawing-App#8]
I have scripted using app-script, but this is my first attempt to really create a full blown app.  So it is very possible that it is user error.

I got your code running on a touch-screen chromebook (using Chrome Dev Editor), and it launches and runs fine with a mouse.  But when I use the touch-screen to draw it doesn't work.  I am only able to click the other elements like color, and size, but drawing doesn't work with touch, only the mouse.

**Comment by williammalone** [comment]
Can you put add "`console.log("test")`" in the `press` and `drag` functions and check the console to see if those functions are firing when you use the touch screen?

**Comment by edlisten** [comment]
I will try it on Monday when I am back at work.  Thank you for the quick
reply.

**Comment by edlisten** [comment]
The console log, shows the same functions running when I use touch or if I
use the mouse.  I am on a touch chromebook if it makes a difference.

I tested a console log with each of the functions associated with the
listeners listed below, and they behave exactly the same as if I was using
the mouse.  Problem is that it is not drawing the lins when I use touch.

canvas.addEventListener("touchstart", press, false);
canvas.addEventListener("touchmove", drag, false);
// canvas.addEventListener("touchend", release, false);
canvas.addEventListener("touchend", release);
canvas.addEventListener("touchcancel", cancel, false);

*Bjorn Behrendt M.Ed ~ Never Stop Learning*
*   bj@edlisten.com <bj@edlisten.com> | **Blog: *Edlisten.com
<http://edlisten.com/>

**Comment by edlisten** [comment]
I did notice that if I just tap the screen, (touch and release without
drag), a round dot does appear.

*Bjorn Behrendt M.Ed ~ Never Stop Learning*
*   bj@edlisten.com <bj@edlisten.com> | **Blog: *Edlisten.com
<http://edlisten.com/>

**Comment by williammalone** [comment]
Try changing these lines in the `press` function:

```
mouseX = e.pageX - this.offsetLeft,
mouseY = e.pageY - this.offsetTop;
```
to this:
```
mouseX = (e.changedTouches ? e.changedTouches[0].pageX : e.pageX) - this.offsetLeft;
mouseY = (e.changedTouches ? e.changedTouches[0].pageY : e.pageY) - this.offsetTop;
```

and change the `drag` function to this:

```
drag = function (e) {
    var mouseX = (e.changedTouches ? e.changedTouches[0].pageX : e.pageX) - this.offsetLeft,
        mouseY = (e.changedTouches ? e.changedTouches[0].pageY : e.pageY) - this.offsetTop;
  
    if (paint) {
        addClick(mouseX, mouseY, true);
        redraw();
    }
    // Prevent the whole page from dragging if on mobile
    e.preventDefault();
},
```
Let me know if that fixes it.

**Comment by edlisten** [comment]
That worked, but I did have to change the ; to a , on mouseX on the press
function.

Error:

mouseX = (e.changedTouches ? e.changedTouches[0].pageX : e.pageX) -
this.offsetLeft; (change ; to ,)


Works:

mouseX = (e.changedTouches ? e.changedTouches[0].pageX : e.pageX) -
this.offsetLeft, (change ; to ,)



*Bjorn Behrendt M.Ed ~ Never Stop Learning*
*   bj@edlisten.com <bj@edlisten.com> | **Blog: *Edlisten.com
<http://edlisten.com/>

**Comment by williammalone** [comment]
Thanks for pointing out that typo! I have updated the code the to include the fix.
